EBA_DATA_SUBMITTER_ROLE = "EBA Data Submitter"
EBA_DATA_ADMIN_ROLE = "EBA Data Admin"


class Schema:
    DES_ALIASES_SCHEMA = "EN6Oh5XSD5_q2Hgu-aqpdfbVepdpYpFlgz6zvJL5b_r5"
    ECR_AUTH_SCHEMA1 = "EH6ekLjSr8V32WyFbGe1zXjTzFs9PkTYmupJ9H65O14g"
    ECR_AUTH_SCHEMA2 = "EJOkgTilEMjPgrEr0yZDS_MScnI0pBb75tO54lvXugOy"
    ECR_SCHEMA = "EHAuBf02w-FIH8yEVrD_qIkgr0uI_rDzZ-kTABmdmUFP"
    ECR_SCHEMA_PROD = "EEy9PkikFcANV1l7EHukCeXqrzT1hNZjGlUk7wuMO5jw"
    LE_SCHEMA1 = "EHyKQS68x_oWy8_vNmYubA5Y0Tse4XMPFggMfoPoERaM"
    LE_SCHEMA2 = "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
    OOR_AUTH_SCHEMA = "EKA57bKBKxr_kN7iN5i7lMUxpMG-s19dRcmov1iDxz-E"
    OOR_SCHEMA = "EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy"
    QVI_SCHEMA1 = "EFgnk_c08WmZGgv9_mpldibRuqFMTQN-rAgtD-TCOwbs"
    QVI_SCHEMA2 = "EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao"
    TEST_SCHEMA = "EBvYkhZOz5qEsUFeAmksUclJSh-c6RmQ92SDaAZhAmLF"

    schema_names = {ECR_AUTH_SCHEMA1: "ECR_AUTH", ECR_AUTH_SCHEMA2: "ECR_AUTH", ECR_SCHEMA: "ECR",
                    ECR_SCHEMA_PROD: "ECR", LE_SCHEMA1: "LE", LE_SCHEMA2: "LE", OOR_AUTH_SCHEMA: "OOR_AUTH",
                    OOR_SCHEMA: "OOR", QVI_SCHEMA1: "QVI", QVI_SCHEMA2: "QVI", TEST_SCHEMA: "ECR"}
