name: Publish Docker image

on:
  push:
    tags:
      - "*"  # Triggers on any tag push
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version (select a tag or enter manually)"
        required: true
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gleif/vlei-verifier

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: images/verifier.dockerfile
          push: true
          tags: |
            gleif/vlei-verifier:${{ env.VERSION }}
          labels: ${{ env.VERSION }}
      - name: Confirm Push
        run:
          echo "Docker image pushed with tag:${{ env.VERSION }}"
